"use client";

import React, { useState, useEffect } from "react";
import { Search, Filter, Download, Mail, FileText, CheckCircle2 } from "lucide-react";
import api from "@/lib/axios";
import { toast } from "react-toastify";

function generateInvoicePDF(inv) {
  import("jspdf").then(({ jsPDF }) => {
    const doc = new jsPDF();
    const pageW = doc.internal.pageSize.getWidth();

    // Header
    doc.setFillColor(15, 23, 42);
    doc.rect(0, 0, pageW, 40, "F");
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(22);
    doc.setFont("helvetica", "bold");
    doc.text("VendorBridge", 20, 22);
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.text("Procurement & Vendor Management ERP", 20, 30);

    // Invoice title
    doc.setTextColor(30, 41, 59);
    doc.setFontSize(16);
    doc.setFont("helvetica", "bold");
    doc.text("INVOICE", 20, 55);
    doc.setFontSize(11);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(100, 116, 139);
    doc.text(inv.invoiceNumber || `INV-${inv.id}`, 20, 63);

    // PO Reference — right side
    doc.setTextColor(30, 41, 59);
    doc.setFontSize(10);
    doc.text(`PO Reference: ${inv.poNumber || "N/A"}`, pageW - 20, 55, { align: "right" });
    doc.text(`Status: ${inv.status}`, pageW - 20, 63, { align: "right" });

    // Divider
    doc.setDrawColor(226, 232, 240);
    doc.line(20, 70, pageW - 20, 70);

    // Details
    let y = 82;
    const addRow = (label, value) => {
      doc.setFont("helvetica", "normal");
      doc.setTextColor(100, 116, 139);
      doc.setFontSize(10);
      doc.text(label, 20, y);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(30, 41, 59);
      doc.text(String(value || "N/A"), 80, y);
      y += 10;
    };

    addRow("Vendor:", inv.vendorName || inv.vendor || "N/A");
    addRow("Amount:", `Rs. ${Number(inv.amount).toLocaleString("en-IN")}`);
    addRow("Issue Date:", inv.created_at ? new Date(inv.created_at).toLocaleDateString("en-IN") : "N/A");
    addRow("Due Date:", inv.dueDate || "N/A");
    addRow("Status:", inv.status);

    // Divider
    y += 5;
    doc.setDrawColor(226, 232, 240);
    doc.line(20, y, pageW - 20, y);
    y += 15;

    // Amount box
    doc.setFillColor(248, 250, 252);
    doc.roundedRect(20, y, pageW - 40, 30, 4, 4, "F");
    doc.setFontSize(12);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(100, 116, 139);
    doc.text("Total Amount Due", 30, y + 13);
    doc.setFontSize(18);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(37, 99, 235);
    doc.text(`Rs. ${Number(inv.amount).toLocaleString("en-IN")}`, pageW - 30, y + 20, { align: "right" });

    // Footer
    y = 270;
    doc.setFontSize(8);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(148, 163, 184);
    doc.text("Generated by VendorBridge ERP", pageW / 2, y, { align: "center" });
    doc.text(`Generated on: ${new Date().toLocaleString("en-IN")}`, pageW / 2, y + 5, { align: "center" });

    doc.save(`${inv.invoiceNumber || "Invoice"}.pdf`);
    toast.success("PDF downloaded!");
  });
}

function generatePOPDF(inv) {
  import("jspdf").then(({ jsPDF }) => {
    const doc = new jsPDF();
    const pageW = doc.internal.pageSize.getWidth();

    // Header
    doc.setFillColor(37, 99, 235);
    doc.rect(0, 0, pageW, 40, "F");
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(22);
    doc.setFont("helvetica", "bold");
    doc.text("VendorBridge", 20, 22);
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.text("Purchase Order Document", 20, 30);

    // PO Title
    doc.setTextColor(30, 41, 59);
    doc.setFontSize(16);
    doc.setFont("helvetica", "bold");
    doc.text("PURCHASE ORDER", 20, 55);
    doc.setFontSize(11);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(100, 116, 139);
    doc.text(inv.poNumber || `PO-${inv.id}`, 20, 63);

    // Right side
    doc.setTextColor(30, 41, 59);
    doc.setFontSize(10);
    doc.text(`Invoice: ${inv.invoiceNumber || "N/A"}`, pageW - 20, 55, { align: "right" });
    doc.text(`Status: ${inv.status}`, pageW - 20, 63, { align: "right" });

    doc.setDrawColor(226, 232, 240);
    doc.line(20, 70, pageW - 20, 70);

    let y = 82;
    const addRow = (label, value) => {
      doc.setFont("helvetica", "normal");
      doc.setTextColor(100, 116, 139);
      doc.setFontSize(10);
      doc.text(label, 20, y);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(30, 41, 59);
      doc.text(String(value || "N/A"), 80, y);
      y += 10;
    };

    addRow("Vendor:", inv.vendorName || inv.vendor || "N/A");
    addRow("PO Number:", inv.poNumber || "N/A");
    addRow("Amount:", `Rs. ${Number(inv.amount).toLocaleString("en-IN")}`);
    addRow("Issue Date:", inv.created_at ? new Date(inv.created_at).toLocaleDateString("en-IN") : "N/A");
    addRow("Due Date:", inv.dueDate || "N/A");

    y += 5;
    doc.setDrawColor(226, 232, 240);
    doc.line(20, y, pageW - 20, y);
    y += 15;

    doc.setFillColor(248, 250, 252);
    doc.roundedRect(20, y, pageW - 40, 30, 4, 4, "F");
    doc.setFontSize(12);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(100, 116, 139);
    doc.text("Order Total", 30, y + 13);
    doc.setFontSize(18);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(37, 99, 235);
    doc.text(`Rs. ${Number(inv.amount).toLocaleString("en-IN")}`, pageW - 30, y + 20, { align: "right" });

    y = 270;
    doc.setFontSize(8);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(148, 163, 184);
    doc.text("Generated by VendorBridge ERP", pageW / 2, y, { align: "center" });
    doc.text(`Generated on: ${new Date().toLocaleString("en-IN")}`, pageW / 2, y + 5, { align: "center" });

    doc.save(`${inv.poNumber || "PurchaseOrder"}.pdf`);
    toast.success("PO PDF downloaded!");
  });
}

export default function InvoicesPage() {
  const [search, setSearch] = useState("");
  const [activeTab, setActiveTab] = useState("all");
  const [invoices, setInvoices] = useState([]);
  const [loading, setLoading] = useState(true);

  const fetchInvoices = async () => {
    try {
      const res = await api.get("/invoices");
      setInvoices(res.data);
    } catch (error) {
      console.error("Failed to fetch invoices:", error);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchInvoices();
  }, []);

  const handleMarkAsPaid = async (id) => {
    try {
      await api.patch(`/invoices/${id}/status`, { status: "Paid" });
      toast.success("Invoice marked as Paid");
      fetchInvoices();
    } catch (error) {
      console.error(error);
      toast.error("Failed to update invoice");
    }
  };

  const filteredInvoices = invoices.filter(inv => {
    const matchesTab = activeTab === "all" || inv.status.toLowerCase() === activeTab;
    const matchesSearch = !search ||
      (inv.invoiceNumber || "").toLowerCase().includes(search.toLowerCase()) ||
      (inv.poNumber || "").toLowerCase().includes(search.toLowerCase()) ||
      (inv.vendorName || "").toLowerCase().includes(search.toLowerCase());
    return matchesTab && matchesSearch;
  });

  const getStatusStyle = (status) => {
    switch(status) {
      case "Paid": return "bg-green-100 text-green-700 border-green-200";
      case "Pending": return "bg-amber-100 text-amber-700 border-amber-200";
      case "Overdue": return "bg-red-100 text-red-700 border-red-200";
      default: return "bg-slate-100 text-slate-700 border-slate-200";
    }
  };

  return (
    <div className="space-y-6">
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <h1 className="text-2xl font-bold text-slate-900 tracking-tight">Purchase Orders & Invoices</h1>
          <p className="text-sm text-slate-500 mt-1">Manage vendor payments and financial documents.</p>
        </div>
      </div>

      <div className="bg-white rounded-2xl shadow-sm border border-slate-100 overflow-hidden">
        
        {/* Tabs */}
        <div className="flex border-b border-slate-100 px-4 pt-2">
          {["all", "pending", "paid", "overdue"].map((tab) => (
            <button
              key={tab}
              onClick={() => setActiveTab(tab)}
              className={`px-4 py-3 text-sm font-medium capitalize border-b-2 transition-colors ${
                activeTab === tab 
                  ? "border-blue-600 text-blue-600" 
                  : "border-transparent text-slate-500 hover:text-slate-700 hover:border-slate-300"
              }`}
            >
              {tab}
            </button>
          ))}
        </div>

        {/* Toolbar */}
        <div className="p-4 border-b border-slate-100 flex flex-col sm:flex-row items-center justify-between gap-4">
          <div className="relative w-full sm:w-96">
            <Search className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" size={18} />
            <input 
              type="text" 
              placeholder="Search invoices or POs..." 
              value={search}
              onChange={(e) => setSearch(e.target.value)}
              className="w-full pl-10 pr-4 py-2 bg-slate-50 border border-slate-200 rounded-lg text-sm text-slate-900 focus:ring-2 focus:ring-blue-500 focus:border-transparent outline-none transition-all"
            />
          </div>
        </div>

        {/* List */}
        <div className="overflow-x-auto">
          <table className="w-full text-sm text-left">
            <thead className="text-xs text-slate-500 uppercase bg-slate-50">
              <tr>
                <th className="px-6 py-4 font-medium">Invoice & PO</th>
                <th className="px-6 py-4 font-medium">Vendor</th>
                <th className="px-6 py-4 font-medium">Amount</th>
                <th className="px-6 py-4 font-medium">Dates</th>
                <th className="px-6 py-4 font-medium">Status</th>
                <th className="px-6 py-4 font-medium text-right">Actions</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-100">
              {loading ? (
                <tr>
                  <td colSpan="6" className="px-6 py-8 text-center text-slate-500">Loading invoices...</td>
                </tr>
              ) : filteredInvoices.length === 0 ? (
                <tr>
                  <td colSpan="6" className="px-6 py-8 text-center text-slate-500">No invoices found.</td>
                </tr>
              ) : (
                filteredInvoices.map((inv) => (
                  <tr key={inv.id} className="hover:bg-slate-50/50 transition-colors group">
                    <td className="px-6 py-4">
                      <div className="flex flex-col">
                        <span className="font-semibold text-slate-900 flex items-center gap-2">
                          <FileText size={16} className="text-slate-400" /> {inv.invoiceNumber || inv.id}
                        </span>
                        <span className="text-xs text-slate-500 mt-1 pl-6">PO: {inv.poNumber}</span>
                      </div>
                    </td>
                    <td className="px-6 py-4 font-medium text-slate-700">{inv.vendorName || inv.vendor}</td>
                    <td className="px-6 py-4 font-bold text-slate-900">₹{Number(inv.amount).toLocaleString()}</td>
                    <td className="px-6 py-4">
                      <div className="flex flex-col text-xs space-y-1">
                        <span className="text-slate-500">Issued: {inv.created_at ? new Date(inv.created_at).toLocaleDateString() : "N/A"}</span>
                        <span className={`font-medium ${inv.status === 'Overdue' ? 'text-red-600' : 'text-slate-700'}`}>Due: {inv.dueDate}</span>
                      </div>
                    </td>
                    <td className="px-6 py-4">
                      <span className={`inline-flex items-center px-2.5 py-1 rounded-full text-xs font-medium border ${getStatusStyle(inv.status)}`}>
                        {inv.status}
                      </span>
                    </td>
                    <td className="px-6 py-4 text-right">
                      <div className="flex items-center justify-end gap-1">
                        <button 
                          onClick={() => generateInvoicePDF(inv)} 
                          className="p-2 text-slate-400 hover:text-blue-600 hover:bg-blue-50 rounded-lg transition-colors" 
                          title="Download Invoice PDF"
                        >
                          <Download size={18} />
                        </button>
                        <button 
                          onClick={() => generatePOPDF(inv)} 
                          className="p-2 text-slate-400 hover:text-indigo-600 hover:bg-indigo-50 rounded-lg transition-colors" 
                          title="Download PO PDF"
                        >
                          <FileText size={18} />
                        </button>
                        {inv.status !== "Paid" && (
                          <button 
                            onClick={() => handleMarkAsPaid(inv.id)} 
                            className="p-2 text-slate-400 hover:text-green-600 hover:bg-green-50 rounded-lg transition-colors" 
                            title="Mark as Paid"
                          >
                            <CheckCircle2 size={18} />
                          </button>
                        )}
                      </div>
                    </td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
}
